// Generated by CoffeeScript 1.6.3
(function() {
  define(["flight/lib/component"], function(defineComponent) {
    var list;
    list = function() {
      this.defaultAttrs({});
      return this.after("initialize", function() {
        return this.$node.html("hello");
      });
    };
    return defineComponent(list);
  });

}).call(this);
