// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    return function(node, fieldName, message) {
      var group, help;
      group = node.find(".control-group[name=" + fieldName + "]");
      help = node.find(".control-group[name=" + fieldName + "] span.help-inline");
      if (message) {
        group.addClass('error');
        return help.html(message);
      } else {
        group.removeClass('error');
        return help.html("");
      }
    };
  });

}).call(this);
